default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode

development:
  <<: *default
  database: agro_development
  username: pguser
  password: admin
  host: localhost

test:
  <<: *default
  database: agro_test
  username: pguser
  password: admin
  host: localhost

production:
  <<: *default
  database: agro_production
